version: '3.8'

services:
  web:
    build:
      context: ./app
    command: /bin/sh -c "/home/app/web/local_entrypoint.sh"
    volumes:
      - ./app:/home/app/web/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`localhost`)"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env

  redis:
    image: redis:7-alpine
    command: /bin/sh -c "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    env_file:
      - ./.env
    ports:
      - 6379:6379
    depends_on:
      - db
  
  traefik:
    image: traefik:v2.9.10
    ports:
      - 80:80
      - 8081:8080
    volumes:
      - "$PWD/traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  flower:
    image: mher/flower
    env_file:
      - ./.env
    ports:
      - 5555:5555
    depends_on:
      - redis

volumes:
  postgres_data:
  app:
